---

name: Build documents
'on':
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/sasanarakkha/document-build-actions:main
    permissions:
      contents: write
    steps:
      - uses: sasanarakkha/document-build-actions@v1
        with: {}
